### PR TITLE
hotfix for horse/wagon inventory issues

### PR DESCRIPTION
**Pull request by ghost**
Tested and recompiled.
[Recording of Test](https://i.imgur.com/tXYdUh6.mp4)
I'll be readily available all this weekend in case something else goes wrong with it. Just @ me here or in Discord.

### CODE REVIEW

**Comment by outsider31000** [comment]
thanks it will be reviewed

**Comment by grimslice** [comment]
Try it from person to person as well when you give item put the entire amount and then spam click the persons name

**Comment by outsider31000** [comment]
that has nothing to do with stables.

**Comment by outsider31000** [comment]
this repo is vorp stables.

**Comment by outsider31000** [comment]
Imaa merge this @bythewood trusting you again lol

**Pull request merged**
