### PR TITLE
added capability to store weapons on horses/wagons

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Tested good for me, however I recommend someone test this elsewhere as well as all my RedM servers are heavily modified.

**Review by Local9 — APPROVED** [review]

**Comment by Local9** [comment]
change looks fine, I would ask in the future, more commits for each method changed.

**Comment by outsider31000** [comment]
thanks for the work! and for local9 to take his time and review it

**Comment by ghost** [comment]
Thanks for cleaning up my mess @Local9! Sorry about that. XD

**Pull request merged**
